version: '3.8'

services:
  #ZOOKEEPER
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - bigdata-net

  #KAFKA
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 524288000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 524288000
    depends_on:
      zookeeper:
        condition: service_started
    networks:
      - bigdata-net

  #NIFI
  nifi:
    image: apache/nifi:1.28.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: "8443"
      NIFI_WEB_HTTPS_HOST: "0.0.0.0"
      NIFI_WEB_PROXY_HOST: "localhost:8443"
      # Vos anciens identifiants
      SINGLE_USER_CREDENTIALS_USERNAME: "55b44eb5-1222-4642-87b8-f71e0eeee359"
      SINGLE_USER_CREDENTIALS_PASSWORD: "/31McaVjFrm9cuLbbkdniAlqGqBD1Yyf"
      NIFI_CLUSTER_IS_NODE: "false"
    volumes:
      - nifi_data:/opt/nifi/nifi-current
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:8443/nifi-api/system-diagnostics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    depends_on:
      kafka:
        condition: service_started
    networks:
      - bigdata-net

  #SPARK MASTER
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./spark-jars:/opt/spark/additional-jars
    networks:
      - bigdata-net

  #SPARK WORKER
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      --webui-port 8081
      --cores 2
      --memory 2G
      spark://spark-master:7077
    volumes:
      - ./spark-jars:/opt/spark/additional-jars
    depends_on:
      - spark-master
    networks:
      - bigdata-net

  #POSTGRESQL
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bigdata-net

  #GRAFANA
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      postgres:
        condition: service_started
    networks:
      - bigdata-net

# Volumes
volumes:
  nifi_data:
  postgres_data:
  grafana_data:

# Réseau
networks:
  bigdata-net:
    driver: bridge